# Generated by Django 2.2 on 2019-11-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id_done',
            field=models.BooleanField(default=False),
        ),
    ]
