# Generated by Django 2.2 on 2019-11-16 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_auto_20191116_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoteUser',
        ),
    ]
