# Generated by Django 2.2 on 2019-11-16 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0004_delete_noteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='note.Note')),
                ('id_user', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
