# Generated by Django 2.2 on 2019-11-16 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_noteuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteuser',
            name='id_user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
