# Generated by Django 2.2 on 2019-11-16 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20191116_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='id_done',
            new_name='is_done',
        ),
    ]
