# Generated by Django 2.2 on 2019-11-17 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0007_auto_20191116_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='id_users',
            field=models.ManyToManyField(blank=True, related_name='users_pinned_to_note', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='NoteUser',
        ),
    ]
