# Generated by Django 2.2 on 2019-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_auto_20191123_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
