# Generated by Django 2.2 on 2019-11-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_note_priority'),
        ('note', '0011_comment'),
    ]

    operations = [
    ]
