# Generated by Django 2.2 on 2019-11-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191124_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='awatar',
            field=models.FileField(blank=True, default='awatar/default-100.png', upload_to='awatar'),
        ),
    ]
